### ISSUE TITLE
runTcellExTRECT returns NA

### ISSUE THREAD

**Issue by anabbi** [McGranahanLab/TcellExTRECT#13]
Hello,

thanks for your great work. I have a few WES files that I wanted to try your tool on. While the tools runs well on the majority of files, it returns `NA` for some of them with no error or message. 

For example, the following is the coverage file from `getCovFromBam`:

[08b61267-9fdc-5c6a-bf85-236fb8057778_wxs_gdc_realn_TCRA.txt](https://github.com/McGranahanLab/TcellExTRECT/files/7550352/08b61267-9fdc-5c6a-bf85-236fb8057778_wxs_gdc_realn_TCRA.txt)

loading the coverage file and running the tool like below returns `NA` :
`cov_df <- loadCov(cov.file)`
`runTcellExTRECT(cov_df, TCRA_exons_hg38, tcra_seg_hg38, 'hg38')`

I suspect there might not be sufficient reads on TRA regions, but I wanted to make sure I am interpreting this correctly.

Thanks for your help

Arash

**Comment by rbentham** [comment]
Hi Arash,

Thank you for your feedback, the tool returns NAs if there are a large number of exons removed in the QC step used in runTcellExTRECT. The parameter median.thresh controls this QC step, its default value is 15 and if the median depth of an exon is below 15 it is removed. If more than 30 exons are removed the sample is flagged as potential low quality and an NA is output. In your example 33 exons are removed and hence NA is returned. 

I have updated runTcellExTRECT to output warning messages describing why NAs have returned to help future users.  In your case you could possible lower the parameter of median.thresh to 10 to make this QC step more lenient, if this sample has lower depth this could make sense as this step is more designed to pick up and remove any exons that have absolutely zero coverage.

**Comment by anabbi** [comment]
Great! Thanks Bobby
