### ISSUE TITLE
failed to generate customed TCRA_exons_hg19

### ISSUE THREAD

**Issue by stroke1989** [McGranahanLab/TcellExTRECT#14]
Excuse me:
Thank you for this brilliant tool!
I tried to use TcellEXTRECT to analyze my own WES data, and I used createExonDFBed to generated TCRA_exons_hg19_custom, however, error occurred as follows:
> bed.file <- '~/mydata/genome/hg19/hg19_bed/S07604514_Regions.v6.hg19.new.bed'
> TCRA_exons_hg19_custom <- createExonDFBed(bed.file, 'hg19')
Rows: 222295 Columns: 3
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): X1
dbl (2): X2, X3

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
In createExonDFBed(bed.file, "hg19") :
  Note: exome capture kits not officially supported by TcellExTRECT may have unknown biases or lack necessary coverage within TCRA locus
the  capture kits that I used is Agilent SureSelect Human All Exon V5 OR V6, I don't know how to handle this issue, I need your help. Hope your reponse! Appreciate!

**Comment by rbentham** [comment]
Hi,

I think the default `data(TCRA_exons_hg19)` (designed for Agilent v4/v5) should still be compatible with v6 so for simplicity you can just use that.

I am also not sure if I quite understand what is going wrong with your use of `createExonDFBed()`? I do not see an error message but it does generates that warning message by default just to raise awareness that the exon capture kit you are using may not have been robustly tested. The function is fairly simple and is just reading in the bed file as a tsv, the output should be a data frame of the capture regions overlapping with the the TCRA locus.

**Comment by stroke1989** [comment]
Excuse me:
I'm sorry to make me unclear. this time, the capture kits I uesed is not offically supported by  TcellExTRECT, therefore, as the document pointed out, TCRA_exons_hg19_custom can be created using createExonDFBed(), the following was what I did:
> bed.file <- '~/mydata/genome/hg19/hg19_bed/S07604514_Regions.v6.hg19.new.bed'
> TCRA_exons_hg19_custom <- createExonDFBed(bed.file, 'hg19')
Rows: 222295 Columns: 3
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): X1
dbl (2): X2, X3

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
In createExonDFBed(bed.file, "hg19") :
  Note: exome capture kits not officially supported by TcellExTRECT may have unknown biases or lack necessary coverage within TCRA locus
> data(TCRA_exons_hg19_custom)
Warning message:
In data(TCRA_exons_hg19_custom) :
  data set ‘TCRA_exons_hg19_custom’ not found
When I runned createExonDFBed(), indeed, no error message was gaved, but instead of warning message, However, TCRA_exons_hg19_custom did not created sucessfully, data() indcated 'TCRA_exons_hg19_custom’ not found

**Comment by lincj1994** [comment]
Hi. I have a follow-up question: for the bed files provided by Agilent (_Covered.bed, _Padded.bed, _Regions.bed), which one should be used to create a customed TCRA_exons_hg38.

**Comment by rbentham** [comment]
I have previously used the '_Regions.bed' file, I am not sure if there would be much difference in using the _Covered.bed file however.
