### ISSUE TITLE
negative values of TCRA.tcell.fraction

### ISSUE THREAD

**Issue by Dagsbio** [McGranahanLab/TcellExTRECT#19]
Hi all, 

Looking into the output table of runTcellExTRECT, I see I have some negative values for the TCRA.tcell.fraction column:
![image](https://user-images.githubusercontent.com/23311037/176020549-160afdf2-53b0-4810-a746-5aab09d4df1d.png)

Is this normal? Are they 0s in fact?

Thank you & Best regards,

David.

**Comment by rbentham** [comment]
Hi David, 

Thank you for your comment.

Yes these are indeed 0s, there is a known issue in the package with floating point errors causing very small negative fractions where the solution should be 0. 

The confidence interval lower and upper values are based on the noise in the model, if the lower value is negative it should be interpreted as there being high uncertainty if there are T cells present or they are at such a low fraction they can not be reliably distinguished from the noise in the data. 

Best,
Bobby

**Comment by Dagsbio** [comment]
Great, thank you for the explanation Bobby.

Best,

David.
