### ISSUE TITLE
data type for 'TCRA_exons_hg38'

### ISSUE THREAD

**Issue by yoshihiko1218** [McGranahanLab/TcellExTRECT#2]
Hi,

Thank you for a cool tool. I was trying to use it to test my WES data. I realized that data type for start and stop column for 'TCRA_exons_hg38' is chr instead of numeric, which will make error running later functions. I just converted it manually but I think modifying it on your side would benefit people who is not familiar with R.

Thank you again!
Yoshii Ma

**Comment by rbentham** [comment]
Hi Yoshii,

Thank you for raising this issue, the TCRA_exons_hg38 object has now been fixed in the latest commit. 

Best,
Bobby
