### ISSUE TITLE
issue in runTcellExTRECT with my own data

### ISSUE THREAD

**Issue by QianhuiXu** [McGranahanLab/TcellExTRECT#21]
Hello,

TcellExTRECT is a wonderful tool！
I ran into an issue with running runTcellExTRECT with my own data.

My command : 
cov_df

A tibble: 41 × 2
        pos reads
      <dbl> <dbl>
 1 22116322     1
 2 22116323     1
 3 22116324     1
 4 22116325     1
 5 22116326     1
 6 22116327     1
 7 22116328     1
 8 22116329     1
 9 22116330     1
10 22116331     1

TCRA.out <- runTcellExTRECT(cov_df, TCRA_exons_hg19, tcra_seg_hg19, 'hg19')

Error: 
Error in UseMethod("distinct") : 
  no applicable method for 'distinct' applied to an object of class "NULL"

My environment:

 version  R version 4.2.1 (2022-06-23)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2022-10-30
 rstudio  2022.07.2+577 Spotted Wakerobin (desktop)
 pandoc   2.19.2 @ /home/shpc_100668/anaconda3/envs/trec/bin/pandoc

 package      * version  date (UTC) lib source
 ade4           1.7-19   2022-04-19 [1] CRAN (R 4.2.1)
 bit            4.0.4    2020-08-04 [1] CRAN (R 4.2.1)
 bit64          4.0.5    2020-08-30 [1] CRAN (R 4.2.1)
 cachem         1.0.6    2021-08-19 [1] CRAN (R 4.2.1)
 callr          3.7.2    2022-08-22 [1] CRAN (R 4.2.1)
 cli            3.4.1    2022-09-23 [1] CRAN (R 4.2.1)
 colorspace     2.0-3    2022-02-21 [1] CRAN (R 4.2.1)
 crayon         1.5.2    2022-09-29 [1] CRAN (R 4.2.1)
 curl           4.3.3    2022-10-06 [1] CRAN (R 4.2.1)
 devtools     * 2.4.5    2022-10-11 [1] CRAN (R 4.2.1)
 digest         0.6.30   2022-10-18 [1] CRAN (R 4.2.1)
 dplyr          1.0.10   2022-09-01 [1] CRAN (R 4.2.1)
 ellipsis       0.3.2    2021-04-29 [1] CRAN (R 4.2.1)
 fansi          1.0.3    2022-03-24 [1] CRAN (R 4.2.1)
 farver         2.1.1    2022-07-06 [1] CRAN (R 4.2.1)
 fastmap        1.1.0    2021-01-25 [1] CRAN (R 4.2.1)
 fs             1.5.2    2021-12-08 [1] CRAN (R 4.2.1)
 generics       0.1.3    2022-07-05 [1] CRAN (R 4.2.1)
 ggplot2        3.3.6    2022-05-03 [1] CRAN (R 4.2.1)
 glue           1.6.2    2022-02-24 [1] CRAN (R 4.2.1)
 gratia       * 0.7.3    2022-05-09 [1] CRAN (R 4.2.1)
 gtable         0.3.1    2022-09-01 [1] CRAN (R 4.2.1)
 hms            1.1.2    2022-08-19 [1] CRAN (R 4.2.1)
 htmltools      0.5.3    2022-07-18 [1] CRAN (R 4.2.1)
 htmlwidgets    1.5.4    2021-09-08 [1] CRAN (R 4.2.1)
 httpuv         1.6.6    2022-09-08 [1] CRAN (R 4.2.1)
 labeling       0.4.2    2020-10-20 [1] CRAN (R 4.2.1)
 later          1.3.0    2021-08-18 [1] CRAN (R 4.2.0)
 lattice        0.20-45  2021-09-22 [1] CRAN (R 4.2.1)
 lifecycle      1.0.3    2022-10-07 [1] CRAN (R 4.2.1)
 magrittr       2.0.3    2022-03-30 [1] CRAN (R 4.2.1)
 MASS           7.3-58.1 2022-08-03 [1] CRAN (R 4.2.1)
 Matrix         1.5-1    2022-09-13 [1] CRAN (R 4.2.1)
 memoise        2.0.1    2021-11-26 [1] CRAN (R 4.2.1)
 mgcv           1.8-41   2022-10-21 [1] CRAN (R 4.2.1)
 mime           0.12     2021-09-28 [1] CRAN (R 4.2.1)
 miniUI         0.1.1.1  2018-05-18 [1] CRAN (R 4.2.1)
 munsell        0.5.0    2018-06-12 [1] CRAN (R 4.2.1)
 mvnfast        0.2.7    2021-05-20 [1] CRAN (R 4.2.1)
 nlme           3.1-160  2022-10-10 [1] CRAN (R 4.2.1)
 patchwork      1.1.2    2022-08-19 [1] CRAN (R 4.2.1)
 pillar         1.8.1    2022-08-19 [1] CRAN (R 4.2.1)
 pkgbuild       1.3.1    2021-12-20 [1] CRAN (R 4.2.1)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.2.1)
 pkgload        1.3.1    2022-10-28 [1] CRAN (R 4.2.1)
 prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.2.1)
 processx       3.8.0    2022-10-26 [1] CRAN (R 4.2.1)
 profvis        0.3.7    2020-11-02 [1] CRAN (R 4.2.1)
 promises       1.2.0.1  2021-02-11 [1] CRAN (R 4.2.1)
 ps             1.7.2    2022-10-26 [1] CRAN (R 4.2.1)
 purrr          0.3.5    2022-10-06 [1] CRAN (R 4.2.1)
 R6             2.5.1    2021-08-19 [1] CRAN (R 4.2.1)
 Rcpp           1.0.9    2022-07-08 [1] CRAN (R 4.2.1)
 readr          2.1.3    2022-10-01 [1] CRAN (R 4.2.1)
 remotes        2.4.2    2021-11-30 [1] CRAN (R 4.2.1)
 rlang          1.0.6    2022-09-24 [1] CRAN (R 4.2.1)
 rprojroot      2.0.3    2022-04-02 [1] CRAN (R 4.2.1)
 rstudioapi     0.14     2022-08-22 [1] CRAN (R 4.2.1)
 scales         1.2.1    2022-08-20 [1] CRAN (R 4.2.1)
 seqinr         4.2-16   2022-05-19 [1] CRAN (R 4.2.1)
 sessioninfo    1.2.2    2021-12-06 [1] CRAN (R 4.2.1)
 shiny          1.7.3    2022-10-25 [1] CRAN (R 4.2.1)
 stringi        1.7.8    2022-07-11 [1] CRAN (R 4.2.1)
 stringr        1.4.1    2022-08-20 [1] CRAN (R 4.2.1)
 TcellExTRECT * 1.0.1    2022-10-30 [1] Github (McGranahanLab/TcellExTRECT@ec81143)
 tibble         3.1.8    2022-07-22 [1] CRAN (R 4.2.1)
 tidyr          1.2.1    2022-09-08 [1] CRAN (R 4.2.1)
 tidyselect     1.2.0    2022-10-10 [1] CRAN (R 4.2.1)
 tzdb           0.3.0    2022-03-28 [1] CRAN (R 4.2.1)
 urlchecker     1.0.1    2021-11-30 [1] CRAN (R 4.2.1)
 usethis      * 2.1.6    2022-05-25 [1] CRAN (R 4.2.1)
 utf8           1.2.2    2021-07-24 [1] CRAN (R 4.2.1)
 vctrs          0.5.0    2022-10-22 [1] CRAN (R 4.2.1)
 vroom          1.6.0    2022-09-30 [1] CRAN (R 4.2.1)
 withr          2.5.0    2022-03-03 [1] CRAN (R 4.2.1)
 xtable         1.8-4    2019-04-21 [1] CRAN (R 4.2.1)
 zoo            1.8-11   2022-09-17 [1] CRAN (R 4.2.1)

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by rbentham** [comment]
Can you attach your entire cov_df data frame? From what you posted it looks like it only contains 41 rows, this suggests that you may not have enough bases with coverage from the TCRA locus to run T cell ExTRECT. Do you know what exon capture kit was used in the sequencing?

**Comment by rbentham** [comment]
I am closing this issue due to lack of response. Please reopen if you require more guidance.
