### ISSUE TITLE
IDT exome support

### ISSUE THREAD

**Issue by BGI2016** [McGranahanLab/TcellExTRECT#24]
Dear,
are you planning to add support for the IDT Exome capture kit in the future? I tried to calculate the T cell content using the IDT Exome capture kit, but the output scores were very low,close to 0.
https://sg.idtdna.com/pages/products/next-generation-sequencing/workflow/xgen-ngs-hybridization-capture/pre-designed-hyb-cap-panels/exome-hyb-panel-v2
Thanks
Best

**Comment by rbentham** [comment]
Hi,

We have found previously the IDT exome capture kit does not have sufficient coverage across the TCRA locus to be compatible with T cell ExTRECT. I would double check the bed file of the exon capture kit that you are using, but having 0 score would indicate that there is no coverage within the V and J segment regions.

**Comment by BGI2016** [comment]
Thank you very much for your reply.
