### ISSUE TITLE
TCRA or TRA

### ISSUE THREAD

**Issue by DarioS** [McGranahanLab/TcellExTRECT#5]
I think the documentation should refer to the gene's current official symbol, according to **H**UGO **G**ene **N**omenclature **C**ommittee.

![image](https://user-images.githubusercontent.com/631218/133368267-d84abb6a-f683-4142-b623-4d5cddbc7121.png)

**Comment by rbentham** [comment]
Thanks, a note on TRA and a link to genecards page has been added to the README
